 CREATE TABLE "JOB_GRADES"
   (           "GRADE_LEVEL" VARCHAR2(3 BYTE),
                "LOWEST_SAL" NUMBER,
                "HIGHEST_SAL" NUMBER
   ) ;
Insert into JOB_GRADES (GRADE_LEVEL,LOWEST_SAL,HIGHEST_SAL) values ('A',1000,2999);
Insert into JOB_GRADES (GRADE_LEVEL,LOWEST_SAL,HIGHEST_SAL) values ('B',3000,5999);
Insert into JOB_GRADES (GRADE_LEVEL,LOWEST_SAL,HIGHEST_SAL) values ('C',6000,9999);
Insert into JOB_GRADES (GRADE_LEVEL,LOWEST_SAL,HIGHEST_SAL) values ('D',10000,14999);
Insert into JOB_GRADES (GRADE_LEVEL,LOWEST_SAL,HIGHEST_SAL) values ('E',15000,24999);
Insert into JOB_GRADES (GRADE_LEVEL,LOWEST_SAL,HIGHEST_SAL) values ('F',25000,40000);